server:
  port: 8088
spring:
  application:
    name: xtradecustomer
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: errors,messages

userAccountService:
  url: http://localhost:8090